
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stack_clone_rails_development


test:
  <<: *default
  database: stack_clone_rails_test


production:
  <<: *default
  database: stack_clone_rails_production
  username: stack_clone_rails
  password: <%= ENV['STACK_CLONE_RAILS_DATABASE_PASSWORD'] %>
